package com.royalcert.royalsys.domain.enums;

public enum WorkflowState {
    // Application & Quote
    APPLICATION_RECEIVED,
    APPLICATION_UNDER_REVIEW,
    APPLICATION_APPROVED,
    APPLICATION_REJECTED,
    QUOTE_DRAFTED,
    QUOTE_ISSUED,
    QUOTE_ACCEPTED,
    QUOTE_REJECTED,

    // Contract
    CONTRACT_DRAFTED,
    CONTRACT_SENT,
    CONTRACT_SIGNED,
    CONTRACT_EFFECTIVE,

    // Project
    PROJECT_CREATED,
    PROJECT_ACTIVE,
    PROJECT_ON_HOLD,
    PROJECT_COMPLETED,
    PROJECT_CANCELLED,

    // Audit
    AUDIT_PLANNED,
    AUDIT_PLAN_ISSUED,
    AUDIT_IN_PROGRESS,
    AUDIT_COMPLETED,
    AUDIT_REPORT_SUBMITTED,

    // Technical Review
    TECHNICAL_REVIEW_PENDING,
    TECHNICAL_REVIEW_IN_PROGRESS,
    TECHNICAL_REVIEW_COMPLETED,
    TECHNICAL_REVIEW_RETURNED,

    // Certification Decision
    DECISION_PENDING,
    DECISION_IN_PROGRESS,
    DECISION_APPROVED,
    DECISION_REJECTED,
    DECISION_DEFERRED,

    // Certificate
    CERTIFICATE_DRAFTED,
    CERTIFICATE_ISSUED,
    CERTIFICATE_SUSPENDED,
    CERTIFICATE_WITHDRAWN,
    CERTIFICATE_EXPIRED,

    // Finding / NC
    FINDING_ISSUED,
    FINDING_RESPONSE_RECEIVED,
    FINDING_UNDER_REVIEW,
    FINDING_CLOSED,
    FINDING_ESCALATED,

    // Invoice
    INVOICE_DRAFTED,
    INVOICE_SENT,
    INVOICE_PARTIALLY_PAID,
    INVOICE_PAID,
    INVOICE_OVERDUE,
    INVOICE_CANCELLED,
    INVOICE_CREDITED
}
